apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: vnjr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vnjr
    app.kubernetes.io/part-of: byoc-app-tqhc
  name: vnjr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: vnjr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: vnjr
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-sqtk-tenant/byoc-app-tqhc/vnjr@sha256:8f0d45265d9bec1bd0136dc1b2a371755044b24c1a30ee80d0c3651c64a81d56
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
